name: Setup and install
description: Common setup steps for actions

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v5
      with:
        node-version-file: '.node-version'

    - shell: bash
      run: pnpm install
