name: Conventional Commits

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

permissions:
  pull-requests: read

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Conventional Commits
        uses: ./
        with:
          token: ${{ github.token }}
          targets: >
            title
            commits
